[CmdletBinding(SupportsShouldProcess)]
param(
  [string]$SshTarget='nas-checkin',
  [string]$RemoteRoot='/volume3/docker/checkin-fabric-v2',
  [string]$BundleDir='outputs/nas-bundle-deploy',
  [bool]$UseWorkerTransport=$false,
  [switch]$ReplaceCompose,
  [string[]]$IncludePaths=@()
)

$ErrorActionPreference='Stop'

function Resolve-Executable {
  param([Parameter(Mandatory)][string[]]$Names)
  foreach($name in $Names){
    $command=Get-Command $name -ErrorAction SilentlyContinue | Select-Object -First 1
    if($null -ne $command){
      if($command.Source){return $command.Source}
      if($command.Path){return $command.Path}
      if($command.Definition){return $command.Definition}
    }
  }
  return $null
}

function Send-TarArchiveOverSsh {
  param(
    [Parameter(Mandatory)][string]$SshPath,
    [Parameter(Mandatory)][string]$Target,
    [Parameter(Mandatory)][string]$RemoteCommand,
    [Parameter(Mandatory)][string]$ArchivePath
  )

  # The NAS accepts SSH exec but does not provide a working scp subsystem.
  # Feed tar through the process byte stream so Windows PowerShell 5.1 cannot
  # decode or re-encode the archive as text.
  if($RemoteCommand.Contains('"')){throw 'RemoteCommand cannot contain double quotes'}
  $startInfo=New-Object System.Diagnostics.ProcessStartInfo
  $startInfo.FileName=$SshPath
  $startInfo.UseShellExecute=$false
  $startInfo.CreateNoWindow=$true
  $startInfo.RedirectStandardInput=$true
  $startInfo.RedirectStandardOutput=$true
  $startInfo.RedirectStandardError=$true
  $arguments=@('-T','-o','BatchMode=yes','-o','ConnectTimeout=15',$Target,$RemoteCommand)
  if($null -ne $startInfo.PSObject.Properties['ArgumentList']){
    foreach($argument in $arguments){[void]$startInfo.ArgumentList.Add($argument)}
  }
  else {
    # Target and command are validated/generated by this script. The command
    # contains shell single quotes but no double quotes, so this is safe on the
    # Windows PowerShell/.NET Framework fallback without ArgumentList.
    $startInfo.Arguments='-T -o BatchMode=yes -o ConnectTimeout=15 ' + $Target + ' "' + $RemoteCommand + '"'
  }

  $process=New-Object System.Diagnostics.Process
  $process.StartInfo=$startInfo
  $archiveStream=$null
  try {
    if(-not $process.Start()){throw 'Unable to start ssh for NAS archive upload'}
    $stdoutTask=$process.StandardOutput.ReadToEndAsync()
    $stderrTask=$process.StandardError.ReadToEndAsync()
    $archiveStream=[IO.File]::OpenRead($ArchivePath)
    $archiveStream.CopyTo($process.StandardInput.BaseStream)
    $process.StandardInput.Close()
    if(-not $process.WaitForExit(300000)){throw 'NAS archive upload timed out while waiting for remote extraction'}
    $stdout=$stdoutTask.GetAwaiter().GetResult()
    $stderr=$stderrTask.GetAwaiter().GetResult()
    if($process.ExitCode -ne 0){
      $detail=([string]$stderr).Trim()
      if(-not $detail){$detail=([string]$stdout).Trim()}
      throw "NAS archive upload failed (ssh exit $($process.ExitCode)): $detail"
    }
  }
  catch {
    try {
      if($process -and -not $process.HasExited){$process.Kill()}
    } catch {}
    throw
  }
  finally {
    if($archiveStream){$archiveStream.Dispose()}
    if($process){$process.Dispose()}
  }
}

$root=Split-Path -Parent $PSScriptRoot
$scopedPaths=@()
if($PSBoundParameters.ContainsKey('IncludePaths') -and $IncludePaths.Count -eq 0){throw 'IncludePaths cannot be empty'}
if($IncludePaths.Count -gt 0){
  $seen=New-Object 'System.Collections.Generic.HashSet[string]' ([StringComparer]::OrdinalIgnoreCase)
  foreach($entry in $IncludePaths){
    $path=($entry -replace '\\','/')
    if($path -cnotmatch '^(src|public)/[A-Za-z0-9_.-]+(?:/[A-Za-z0-9_.-]+)*$' -or $path.Split('/') -contains '..' -or $path.Split('/') -contains '.' -or -not $seen.Add($path)){
      throw "Invalid or duplicate IncludePaths entry: $entry"
    }
    $source=Join-Path $root ($path -replace '/','\')
    if(-not (Test-Path -LiteralPath $source -PathType Leaf)){throw "IncludePaths file is missing: $entry"}
    $cursor=$root
    foreach($part in $path.Split('/')){
      $cursor=Join-Path $cursor $part
      $item=Get-Item -LiteralPath $cursor -Force
      if(($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0){throw "IncludePaths cannot contain links: $entry"}
    }
    $scopedPaths+=$path
  }
}
& node --check (Join-Path $root 'public/app.js')
if($LASTEXITCODE -ne 0){throw 'Dashboard syntax check failed; deployment stopped'}
& node (Join-Path $root 'scripts/check-ui-navigation.mjs')
if($LASTEXITCODE -ne 0){throw 'Dashboard browser interaction check failed; deployment stopped'}
if(-not $PSCmdlet.ShouldProcess($RemoteRoot,'Deploy V2 dashboard code')){
  Write-Output 'WhatIf: no NAS files or containers changed.'
  return
}
if($SshTarget -notmatch '^[A-Za-z0-9_.-]+$'){throw 'SshTarget is invalid'}
if($RemoteRoot -notmatch '^/volume3/docker/[A-Za-z0-9_.-]+$'){throw 'RemoteRoot is invalid'}
if($RemoteRoot -match '/(?:\.|\.\.)$' -or $BundleDir -notmatch '^outputs[\\/][A-Za-z0-9_.-]+$'){throw 'deployment path is invalid'}
$ssh=Resolve-Executable -Names @('ssh.exe','ssh')
$tar=Resolve-Executable -Names @('tar.exe','tar')
if(-not $ssh){throw 'ssh is required'}
if(-not $tar){throw 'tar.exe is required to create the binary NAS upload archive'}

$bundle=Join-Path $root $BundleDir
& node (Join-Path $root 'scripts\export-nas-bundle.mjs') --out $bundle | Out-Null
if(-not (Test-Path -LiteralPath (Join-Path $bundle 'src') -PathType Container)){throw 'NAS bundle is incomplete'}

# Keep deployment compatible with an older locally cached export helper by
# adding the overlay when it is absent from the generated, ignored bundle.
$overlaySource=Join-Path $root 'compose.worker.yaml'
$overlayTarget=Join-Path $bundle 'compose.worker.yaml'
if((Test-Path -LiteralPath $overlaySource -PathType Leaf) -and -not (Test-Path -LiteralPath $overlayTarget -PathType Leaf)){
  Copy-Item -LiteralPath $overlaySource -Destination $overlayTarget -Force
}

$items=@('Dockerfile','compose.nas.yaml','.dockerignore','package.json','package-lock.json','release.json','src','public','TRANSFER-MANIFEST.txt')
if($UseWorkerTransport){$items=@('Dockerfile','compose.nas.yaml','compose.worker.yaml','.dockerignore','package.json','package-lock.json','release.json','src','public','TRANSFER-MANIFEST.txt')}
if($scopedPaths.Count -gt 0){$items=$scopedPaths}
else {
  # A shell helper keeps full-tree replacement and rollback independently
  # testable. Normalize its line endings for POSIX sh after Windows checkout.
  $treeHelper=Join-Path $PSScriptRoot 'nas-code-release.sh'
  $helperText=[IO.File]::ReadAllText($treeHelper).Replace("`r`n","`n")
  [IO.File]::WriteAllText((Join-Path $bundle 'nas-code-release.sh'),$helperText,[Text.UTF8Encoding]::new($false))
  $items+='nas-code-release.sh'
}
foreach($item in $items){
  if(-not (Test-Path -LiteralPath (Join-Path $bundle $item))){throw "NAS bundle item is missing: $item"}
}

$stamp=Get-Date -Format 'yyyyMMdd-HHmmss'
$stage="$RemoteRoot/.staging/code-$stamp-$([guid]::NewGuid().ToString('N'))"
$releaseId="$stamp-$([guid]::NewGuid().ToString('N'))"
$remoteBackup="$RemoteRoot/backups/code-$releaseId.tar.gz"
$remoteTransaction="$RemoteRoot/backups/code-$releaseId.tree"
$archive=Join-Path ([IO.Path]::GetTempPath()) "checkin-fabric-v2-$stamp-$([guid]::NewGuid().ToString('N')).tar.gz"
$stageCreated=$false
$backupReady=$false
$deployStarted=$false
$codeTreeReady=$false

try {
  & $ssh -o BatchMode=yes -o ConnectTimeout=15 $SshTarget "sudo -n install -d -m 0700 '$stage' && sudo -n chown `$(id -u):`$(id -g) '$stage'"
  if($LASTEXITCODE -ne 0){throw 'NAS staging directory creation failed'}
  $stageCreated=$true
  $remotePreflight="sudo -n test -d '$RemoteRoot' && sudo -n mkdir -p '$RemoteRoot/backups'"
  if($UseWorkerTransport){$remotePreflight += " && sudo -n test -d '$RemoteRoot/transport-config' && sudo -n test -f '$RemoteRoot/transport-config/worker-registry.json' && sudo -n test -d '$RemoteRoot/transport-data'"}
  if($scopedPaths.Count -gt 0){
    foreach($path in $scopedPaths){
      $prefix=''
      foreach($part in $path.Split('/')){
        $prefix=if($prefix){"$prefix/$part"}else{$part}
        $remotePreflight+=" && sudo -n test ! -L '$RemoteRoot/$prefix'"
      }
    }
  }
  & $ssh -o BatchMode=yes -o ConnectTimeout=15 $SshTarget $remotePreflight
  if($LASTEXITCODE -ne 0){throw 'NAS preflight failed'}

  & $tar -czf $archive -C $bundle @items
  if($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $archive -PathType Leaf)){throw 'NAS bundle archive creation failed'}
  # Windows PowerShell 5.1 prepends UTF-8's BOM when a redirected process
  # stdin writer is created. Stage the bytes first, then strip the BOM only
  # when the remote magic bytes prove it is present; PowerShell 7 archives are
  # extracted unchanged.
  $remoteExtract = 'set -eu; archive=' + $stage + '/.bundle.tar.gz; cat > $archive; magic=$(od -An -tx1 -N3 $archive | tr -d '' \n''); case $magic in efbbbf) tail -c +4 $archive | tar -xzf - -C ' + $stage + ';; 1f8b08) tar -xzf $archive -C ' + $stage + ';; *) exit 2;; esac; rm -f $archive'
  Send-TarArchiveOverSsh -SshPath $ssh -Target $SshTarget -RemoteCommand $remoteExtract -ArchivePath $archive

  if($PSCmdlet.ShouldProcess($RemoteRoot,'Backup and deploy V2 code')){
    $backupItems=@('src','public','package.json','package-lock.json','Dockerfile','compose.nas.yaml','.dockerignore');if($UseWorkerTransport){$backupItems+='compose.worker.yaml'}
    $backupList=$backupItems -join ' '
    $backupCommand="set -eu; cd '$RemoteRoot'; for deploy_item in $backupList release.json; do if test -e " + '"$deploy_item"' + "; then printf '%s\n' " + '"$deploy_item"' + "; fi; done | sudo -n tar -czf '$remoteBackup' -T -"
    & $ssh -o BatchMode=yes -o ConnectTimeout=15 $SshTarget $backupCommand
    if($LASTEXITCODE -ne 0){throw 'NAS code backup failed'}
    $backupReady=$true
    $composeFiles="-f '$RemoteRoot/compose.nas.yaml'"
    if($UseWorkerTransport){
      $composeFiles += " -f '$RemoteRoot/compose.worker.yaml'"
    }
    if($scopedPaths.Count -gt 0){
      $installCommands=@()
      foreach($path in $scopedPaths){
        $parent=[IO.Path]::GetDirectoryName($path).Replace('\','/')
        $prefix=''
        foreach($part in $path.Split('/')){
          $prefix=if($prefix){"$prefix/$part"}else{$part}
          $installCommands+="sudo -n test ! -L '$RemoteRoot/$prefix'"
        }
        $installCommands+="sudo -n mkdir -p '$RemoteRoot/$parent'"
        $installCommands+="sudo -n install -m 0644 '$stage/$path' '$RemoteRoot/$path'"
      }
      $deploy="set -eu; $($installCommands -join '; '); sudo -n docker compose $composeFiles up -d --build --force-recreate --no-deps checkin-fabric-dashboard"
    }
    else {
      $replaceMode=if($ReplaceCompose){'1'}else{'0'}
      $workerMode=if($UseWorkerTransport){'1'}else{'0'}
      & $ssh -o BatchMode=yes -o ConnectTimeout=15 $SshTarget "sudo -n sh '$stage/nas-code-release.sh' prepare '$RemoteRoot' '$stage' '$remoteTransaction' '$replaceMode' '$workerMode'"
      if($LASTEXITCODE -ne 0){throw "NAS code transaction preparation failed; backup=$remoteBackup"}
      $codeTreeReady=$true
      $deploy="set -eu; sudo -n sh '$remoteTransaction/recover.sh' apply '$RemoteRoot' '$remoteTransaction'; sudo -n docker compose $composeFiles up -d --build --force-recreate --no-deps checkin-fabric-dashboard"
    }
    $deployStarted=$true
    & $ssh -o BatchMode=yes -o ConnectTimeout=15 $SshTarget $deploy
    if($LASTEXITCODE -ne 0){throw "NAS deployment failed; backup=$remoteBackup"}
    $healthy=$false
    for($attempt=0;$attempt -lt 18;$attempt++){
      $health=& $ssh -o BatchMode=yes -o ConnectTimeout=15 $SshTarget "sudo -n docker inspect --format '{{.State.Health.Status}}' checkin-fabric-dashboard"
      if($LASTEXITCODE -eq 0 -and ([string]$health).Trim() -eq 'healthy'){$healthy=$true;break}
      Start-Sleep -Seconds 5
    }
    if(-not $healthy){throw "NAS health is not healthy; backup=$remoteBackup"}
    Write-Output "NAS V2 code deployed; backup=$remoteBackup; codeTransaction=$(if($codeTreeReady){$remoteTransaction}else{'scoped'})"
  }
  else {
    Write-Output "WhatIf: bundle uploaded to $stage; no deployment performed."
  }
}
catch {
  $failure=$_
  if($backupReady -and $deployStarted){
    Write-Warning "Deployment failed; restoring NAS code backup $remoteBackup"
    $rollbackCompose="-f '$RemoteRoot/compose.nas.yaml'"
    if($UseWorkerTransport){$rollbackCompose+=" -f '$RemoteRoot/compose.worker.yaml'"}
    $removeSelected=if($scopedPaths.Count){($scopedPaths | ForEach-Object { "sudo -n rm -f '$RemoteRoot/$_'" }) -join '; '}else{':' }
    $restoreConfig=if($ReplaceCompose){''}else{' --exclude=compose.nas.yaml --exclude=compose.worker.yaml'}
    $restoreCode=if($codeTreeReady){"sudo -n sh '$remoteTransaction/recover.sh' rollback '$RemoteRoot' '$remoteTransaction'"}else{"$removeSelected; sudo -n tar -xzf '$remoteBackup' -C '$RemoteRoot'$restoreConfig"}
    & $ssh -o BatchMode=yes -o ConnectTimeout=15 $SshTarget "set -eu; $restoreCode; sudo -n docker compose $rollbackCompose up -d --build --force-recreate --no-deps checkin-fabric-dashboard"
    if($LASTEXITCODE -ne 0){Write-Warning "Automatic rollback failed; backup remains at $remoteBackup"}
  }
  throw $failure
}
finally {
  if(Test-Path -LiteralPath $archive -PathType Leaf){Remove-Item -LiteralPath $archive -Force -ErrorAction SilentlyContinue}
  if($stageCreated){
    try {& $ssh -o BatchMode=yes -o ConnectTimeout=15 $SshTarget "sudo -n rm -rf '$stage'" | Out-Null} catch {}
  }
}
