[CmdletBinding(SupportsShouldProcess)]
param(
  [string]$SshTarget='ugreen-nas-cpa',
  [string]$RemoteRoot='/volume3/docker/checkin-fabric-v2',
  [string]$BundleDir='outputs/nas-bundle-deploy',
  [bool]$UseWorkerTransport=$true
)

$ErrorActionPreference='Stop'

function Resolve-Executable {
  param([Parameter(Mandatory)][string[]]$Names)
  foreach($name in $Names){
    $command=Get-Command $name -ErrorAction SilentlyContinue | Select-Object -First 1
    if($null -ne $command){
      if($command.Source){return $command.Source}
      if($command.Path){return $command.Path}
      if($command.Definition){return $command.Definition}
    }
  }
  return $null
}

function Send-TarArchiveOverSsh {
  param(
    [Parameter(Mandatory)][string]$SshPath,
    [Parameter(Mandatory)][string]$Target,
    [Parameter(Mandatory)][string]$RemoteCommand,
    [Parameter(Mandatory)][string]$ArchivePath
  )

  # The NAS accepts SSH exec but does not provide a working scp subsystem.
  # Feed tar through the process byte stream so Windows PowerShell 5.1 cannot
  # decode or re-encode the archive as text.
  if($RemoteCommand.Contains('"')){throw 'RemoteCommand cannot contain double quotes'}
  $startInfo=New-Object System.Diagnostics.ProcessStartInfo
  $startInfo.FileName=$SshPath
  $startInfo.UseShellExecute=$false
  $startInfo.CreateNoWindow=$true
  $startInfo.RedirectStandardInput=$true
  $startInfo.RedirectStandardOutput=$true
  $startInfo.RedirectStandardError=$true
  $arguments=@('-T','-o','BatchMode=yes','-o','ConnectTimeout=15',$Target,$RemoteCommand)
  if($null -ne $startInfo.PSObject.Properties['ArgumentList']){
    foreach($argument in $arguments){[void]$startInfo.ArgumentList.Add($argument)}
  }
  else {
    # Target and command are validated/generated by this script. The command
    # contains shell single quotes but no double quotes, so this is safe on the
    # Windows PowerShell/.NET Framework fallback without ArgumentList.
    $startInfo.Arguments='-T -o BatchMode=yes -o ConnectTimeout=15 ' + $Target + ' "' + $RemoteCommand + '"'
  }

  $process=New-Object System.Diagnostics.Process
  $process.StartInfo=$startInfo
  $archiveStream=$null
  try {
    if(-not $process.Start()){throw 'Unable to start ssh for NAS archive upload'}
    $stdoutTask=$process.StandardOutput.ReadToEndAsync()
    $stderrTask=$process.StandardError.ReadToEndAsync()
    $archiveStream=[IO.File]::OpenRead($ArchivePath)
    $copyTask=$archiveStream.CopyToAsync($process.StandardInput.BaseStream)
    if(-not $copyTask.Wait(300000)){throw 'NAS archive upload timed out while sending bytes'}
    $copyTask.GetAwaiter().GetResult()
    $process.StandardInput.Close()
    if(-not $process.WaitForExit(300000)){throw 'NAS archive upload timed out while waiting for remote extraction'}
    $stdout=$stdoutTask.GetAwaiter().GetResult()
    $stderr=$stderrTask.GetAwaiter().GetResult()
    if($process.ExitCode -ne 0){
      $detail=([string]$stderr).Trim()
      if(-not $detail){$detail=([string]$stdout).Trim()}
      throw "NAS archive upload failed (ssh exit $($process.ExitCode)): $detail"
    }
  }
  catch {
    try {
      if($process -and -not $process.HasExited){$process.Kill()}
    } catch {}
    throw
  }
  finally {
    if($archiveStream){$archiveStream.Dispose()}
    if($process){$process.Dispose()}
  }
}

$root=Split-Path -Parent $PSScriptRoot
if(-not $PSCmdlet.ShouldProcess($RemoteRoot,'Deploy V2 dashboard code')){
  Write-Output 'WhatIf: no NAS files or containers changed.'
  return
}
if($SshTarget -notmatch '^[A-Za-z0-9_.-]+$'){throw 'SshTarget is invalid'}
if($RemoteRoot -notmatch '^/volume3/docker/[A-Za-z0-9_.-]+$'){throw 'RemoteRoot is invalid'}
if($RemoteRoot -match '/(?:\.|\.\.)$' -or $BundleDir -notmatch '^outputs[\\/][A-Za-z0-9_.-]+$'){throw 'deployment path is invalid'}
$ssh=Resolve-Executable -Names @('ssh.exe','ssh')
$tar=Resolve-Executable -Names @('tar.exe','tar')
if(-not $ssh){throw 'ssh is required'}
if(-not $tar){throw 'tar.exe is required to create the binary NAS upload archive'}

$bundle=Join-Path $root $BundleDir
& node (Join-Path $root 'scripts\export-nas-bundle.mjs') --out $bundle | Out-Null
if(-not (Test-Path -LiteralPath (Join-Path $bundle 'src') -PathType Container)){throw 'NAS bundle is incomplete'}

# Keep deployment compatible with an older locally cached export helper by
# adding the overlay when it is absent from the generated, ignored bundle.
$overlaySource=Join-Path $root 'compose.worker.yaml'
$overlayTarget=Join-Path $bundle 'compose.worker.yaml'
if((Test-Path -LiteralPath $overlaySource -PathType Leaf) -and -not (Test-Path -LiteralPath $overlayTarget -PathType Leaf)){
  Copy-Item -LiteralPath $overlaySource -Destination $overlayTarget -Force
}

$items=@('Dockerfile','compose.nas.yaml','.dockerignore','package.json','package-lock.json','src','public','TRANSFER-MANIFEST.txt')
if($UseWorkerTransport){$items=@('Dockerfile','compose.nas.yaml','compose.worker.yaml','.dockerignore','package.json','package-lock.json','src','public','TRANSFER-MANIFEST.txt')}
foreach($item in $items){
  if(-not (Test-Path -LiteralPath (Join-Path $bundle $item))){throw "NAS bundle item is missing: $item"}
}

$stamp=Get-Date -Format 'yyyyMMdd-HHmmss'
$stage="/home/wushuai0802/checkin-fabric-v2-deploy-$stamp-$([guid]::NewGuid().ToString('N'))"
$remoteBackup="$RemoteRoot/backups/code-$stamp.tar.gz"
$archive=Join-Path ([IO.Path]::GetTempPath()) "checkin-fabric-v2-$stamp-$([guid]::NewGuid().ToString('N')).tar.gz"
$stageCreated=$false

try {
  & $ssh -o BatchMode=yes -o ConnectTimeout=15 $SshTarget "mkdir -p '$stage'"
  if($LASTEXITCODE -ne 0){throw 'NAS staging directory creation failed'}
  $stageCreated=$true
  $remotePreflight="sudo -n test -d '$RemoteRoot' && sudo -n mkdir -p '$RemoteRoot/backups'"
  if($UseWorkerTransport){$remotePreflight += " && sudo -n test -d '$RemoteRoot/transport-config' && sudo -n test -f '$RemoteRoot/transport-config/worker-registry.json' && sudo -n test -d '$RemoteRoot/transport-data'"}
  & $ssh -o BatchMode=yes -o ConnectTimeout=15 $SshTarget $remotePreflight
  if($LASTEXITCODE -ne 0){throw 'NAS preflight failed'}

  & $tar -czf $archive -C $bundle @items
  if($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $archive -PathType Leaf)){throw 'NAS bundle archive creation failed'}
  Send-TarArchiveOverSsh -SshPath $ssh -Target $SshTarget -RemoteCommand "tar -xzf - -C '$stage'" -ArchivePath $archive

  if($PSCmdlet.ShouldProcess($RemoteRoot,'Backup and deploy V2 code')){
    $backupItems=@('src','public','package.json','package-lock.json','Dockerfile','compose.nas.yaml','.dockerignore');if($UseWorkerTransport){$backupItems+='compose.worker.yaml'}
    $backupList=$backupItems -join ' '
    & $ssh -o BatchMode=yes -o ConnectTimeout=15 $SshTarget "sudo -n tar -czf '$remoteBackup' -C '$RemoteRoot' $backupList"
    if($LASTEXITCODE -ne 0){throw 'NAS code backup failed'}
    $workerInstall='';$composeFiles="-f '$RemoteRoot/compose.nas.yaml'"
    if($UseWorkerTransport){$workerInstall=" sudo -n install -m 0644 '$stage/compose.worker.yaml' '$RemoteRoot/compose.worker.yaml';";$composeFiles += " -f '$RemoteRoot/compose.worker.yaml'"}
    $deploy="set -eu; sudo -n mkdir -p '$RemoteRoot/src' '$RemoteRoot/public'; sudo -n cp -a '$stage/src/.' '$RemoteRoot/src/'; sudo -n cp -a '$stage/public/.' '$RemoteRoot/public/'; sudo -n install -m 0644 '$stage/package.json' '$RemoteRoot/package.json'; sudo -n install -m 0644 '$stage/package-lock.json' '$RemoteRoot/package-lock.json'; sudo -n install -m 0644 '$stage/Dockerfile' '$RemoteRoot/Dockerfile'; sudo -n install -m 0644 '$stage/compose.nas.yaml' '$RemoteRoot/compose.nas.yaml';$workerInstall sudo -n install -m 0644 '$stage/.dockerignore' '$RemoteRoot/.dockerignore'; sudo -n install -m 0644 '$stage/TRANSFER-MANIFEST.txt' '$RemoteRoot/TRANSFER-MANIFEST.txt'; sudo -n docker compose $composeFiles up -d --build --force-recreate checkin-fabric-dashboard; sudo -n rm -rf '$stage'"
    & $ssh -o BatchMode=yes -o ConnectTimeout=15 $SshTarget $deploy
    if($LASTEXITCODE -ne 0){throw "NAS deployment failed; backup=$remoteBackup"}
    $healthy=$false
    for($attempt=0;$attempt -lt 18;$attempt++){
      $health=& $ssh -o BatchMode=yes -o ConnectTimeout=15 $SshTarget "sudo -n docker inspect --format '{{.State.Health.Status}}' checkin-fabric-dashboard"
      if($LASTEXITCODE -eq 0 -and ([string]$health).Trim() -eq 'healthy'){$healthy=$true;break}
      Start-Sleep -Seconds 5
    }
    if(-not $healthy){throw "NAS health is not healthy; backup=$remoteBackup"}
    Write-Output "NAS V2 code deployed; backup=$remoteBackup"
  }
  else {
    Write-Output "WhatIf: bundle uploaded to $stage; no deployment performed."
  }
}
finally {
  if(Test-Path -LiteralPath $archive -PathType Leaf){Remove-Item -LiteralPath $archive -Force -ErrorAction SilentlyContinue}
  if($stageCreated){
    try {& $ssh -o BatchMode=yes -o ConnectTimeout=15 $SshTarget "rm -rf '$stage'" | Out-Null} catch {}
  }
}
