import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluateCanaryGate} from '../src/canary-gate.mjs';
import {taskIdentity,planHash} from '../src/contracts.mjs';
function fixture(){const id=taskIdentity({businessDate:'2026-09-08',logicalSiteKey:'https://fixture.example',accountKey:'primary'});const task={...id,taskId:id.taskId,origin:'https://fixture.example',logicalSiteKey:'https://fixture.example',accountKey:'primary',businessDate:'2026-09-08',actionType:'checkin',observedStatus:'signed',executionOwner:'legacy-checkin',identity:{userId:'7',source:'user-self'}};return {mode:'shadow_read_only',generatedAt:'2026-09-08T01:00:00Z',businessDate:'2026-09-08',tasks:[task],planHash:planHash([task]),health:{healthy:true,sourceCheckedAt:'2026-09-08T01:00:00Z',freshness:{fresh:true,maxAgeHours:26}},task};}
const worker={profileIsolation:true,executionModes:['execute'],allowedOrigins:['https://fixture.example']};
test('current beta state is denied even for a signed task',()=>{const f=fixture();const r=evaluateCanaryGate({snapshot:f,acceptance:{accepted:false,eligibleRecentDays:3,invalidRecords:[]},worker,taskId:f.task.taskId,now:'2026-09-08T01:00:00Z'});assert.equal(r.accepted,false);assert.ok(r.reasons.includes('shadow_acceptance_incomplete'));assert.equal(r.executionEnabled,false);});
test('stale health, unknown identity and current ownership deny canary',()=>{const f=fixture();f.health.sourceCheckedAt='2026-09-06T01:00:00Z';f.tasks[0].identity.source='browser-cache';const r=evaluateCanaryGate({snapshot:f,acceptance:{accepted:true,eligibleRecentDays:7,invalidRecords:[]},worker,taskId:f.task.taskId,now:'2026-09-08T01:00:00Z'});assert.ok(r.reasons.includes('health_stale'));assert.ok(r.reasons.includes('identity_not_live_verified'));});
test('a fully qualified gate result is still advisory and never enables execution',()=>{const f=fixture();const r=evaluateCanaryGate({snapshot:f,acceptance:{accepted:true,eligibleRecentDays:7,invalidRecords:[],ownerConflictRecords:0},worker,taskId:f.task.taskId,now:'2026-09-08T01:00:00Z'});assert.equal(r.accepted,true);assert.equal(r.executionEnabled,false);assert.equal(r.leaseGranted,false);});
test('monitor-only/unknown/not-started tasks cannot be selected',()=>{const f=fixture();for(const status of ['unknown','not_started','needs_attention']){f.tasks[0].observedStatus=status;const r=evaluateCanaryGate({snapshot:f,acceptance:{accepted:true,eligibleRecentDays:7,invalidRecords:[]},worker,taskId:f.task.taskId,now:'2026-09-08T01:00:00Z'});assert.equal(r.accepted,false);assert.ok(r.reasons.includes('task_not_terminal'));}}
);
