import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {buildSnapshot,writeSnapshot} from '../src/bridge.mjs';
import {createLedgerRecord,appendLedgerRecord} from '../src/shadow-ledger.mjs';
import {commitDashboardGeneration,readDashboardGeneration} from '../src/dashboard-generation.mjs';
const legacyRoot=fileURLToPath(new URL('./fixtures/legacy/',import.meta.url));
test('generation commit pins the snapshot and ledger prefix; restart can recover previous publication',t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'paired-generation-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
  const snapshotFile=path.join(root,'shadow-beta-snapshot.json'),ledgerFile=path.join(root,'shadow-ledger.jsonl');
  const first=buildSnapshot({legacyRoot,generatedAt:'2026-09-02T14:00:00Z'});
  const second=buildSnapshot({legacyRoot,generatedAt:'2026-09-03T14:00:00Z'});
  const append=snapshot=>appendLedgerRecord(ledgerFile,createLedgerRecord(snapshot,{recordedAt:snapshot.generatedAt}),{legacyRoot});
  append(first);writeSnapshot(first,snapshotFile,legacyRoot);commitDashboardGeneration({snapshot:first,snapshotFile,ledgerFile});
  append(second);writeSnapshot(second,snapshotFile,legacyRoot);
  assert.equal(readDashboardGeneration(root).current.snapshot.snapshotId,first.snapshotId);
  assert.equal(readDashboardGeneration(root).ledger.records.length,1);
  commitDashboardGeneration({snapshot:second,snapshotFile,ledgerFile});
  assert.equal(readDashboardGeneration(root).current.snapshot.snapshotId,second.snapshotId);
  fs.writeFileSync(path.join(root,'dashboard-generation.json'),'{');
  const recovered=readDashboardGeneration(root);assert.equal(recovered.stale,true);
  assert.equal(recovered.current.snapshot.snapshotId,first.snapshotId);assert.equal(recovered.ledger.records.length,1);
  fs.appendFileSync(ledgerFile,'truncated JSON');
  assert.equal(readDashboardGeneration(root).current.snapshot.snapshotId,first.snapshotId);
  fs.writeFileSync(ledgerFile,'{}');
  assert.throws(()=>readDashboardGeneration(root),/no complete/);
});
